apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gsyncd.fullname" . }}-nfs-server
  labels:
    app: {{ template "gsyncd.name" . }}-nfs-server
    chart: {{ template "gsyncd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "gsyncd.name" . }}-nfs-server
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gsyncd.name" . }}-nfs-server
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: volume-nfs
        image: gcr.io/google_containers/volume-nfs:0.8
        imagePullPolicy: IfNotPresent
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /mnt
          name: persistent-volume
      volumes:
      - name: persistent-volume
        persistentVolumeClaim:
          claimName: {{ template "gsyncd.fullname" . }}-persistent-volume