apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-dags-nfs-server
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      role: airflow-dags-nfs-server
  template:
    metadata:
      labels:
        role: airflow-dags-nfs-server
    spec:
      containers:
      - name: volume-nfs
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /mnt
          name: persistent-volume
      volumes:
      - name: persistent-volume
        persistentVolumeClaim:
          claimName: airflow-dags-persistent-volume
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-logs-nfs-server
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      role: airflow-logs-nfs-server
  template:
    metadata:
      labels:
        role: airflow-logs-nfs-server
    spec:
      containers:
      - name: volume-nfs
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /mnt
          name: persistent-volume
      volumes:
      - name: persistent-volume
        persistentVolumeClaim:
          claimName: airflow-logs-persistent-volume