apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-nfs-persistent-volume
  namespace: airflow
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: airflow-dags-nfs-server-service-headless.airflow.svc.cluster.local
    path: "/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-nfs-persistent-volume
  namespace: airflow
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: airflow-logs-nfs-server-service-headless.airflow.svc.cluster.local
    path: "/"