apiVersion: v1
kind: Service
metadata:
  name: airflow-dags-nfs-server-service-headless
  namespace: airflow
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: airflow-dags-nfs-server
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-logs-nfs-server-service-headless
  namespace: airflow
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: airflow-logs-nfs-server